INSERT INTO category (cateName) VALUES ("소설/장르문학");
INSERT INTO category (cateName) VALUES ("예술/대중문화");
INSERT INTO category (cateName) VALUES ("에세이/시");
INSERT INTO category (cateName) VALUES ("만화/그래픽노블");
INSERT INTO category (cateName) VALUES ("외국어");
INSERT INTO category (cateName) VALUES ("경영/경제");
INSERT INTO category (cateName) VALUES ("역사/법");
INSERT INTO category (cateName) VALUES ("정치/사회과학");
INSERT INTO category (cateName) VALUES ("컴퓨터/인터넷/기술");
INSERT INTO category (cateName) VALUES ("자연과학");
INSERT INTO category (cateName) VALUES ("종교");
INSERT INTO category (cateName) VALUES ("어린이/청소년");
INSERT INTO category (cateName) VALUES ("가정/생활");
INSERT INTO category (cateName) VALUES ("건강/스포츠");
INSERT INTO category (cateName) VALUES ("자기계발");
INSERT INTO category (cateName) VALUES ("해외도서/잡지");

INSERT INTO language (language) VALUES ("한국어");
INSERT INTO language (language) VALUES ("영어");
INSERT INTO language (language) VALUES ("일본어");
INSERT INTO language (language) VALUES ("중국어");
INSERT INTO language (language) VALUES ("스페인어");
INSERT INTO language (language) VALUES ("프랑스어");
INSERT INTO language (language) VALUES ("아랍어");

INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("Moby Dick", "Herman Melville", "Public Domain", 0, 544, 117, 209, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid,  bookUrl, bookImage) values ("Little Women; Or, Meg, Jo, Beth, and Amy", "Louisa May Alcott", "Public Domain", 0, 373, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("Metamorphosis", "Franz Kafka", "Public Domain", 0, 80, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("Frankenstein", "Mary Wollstonecraft Shelley", "Public Domain", 0, 500, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("A Doll's House", "Henrik Ibsen", "Public Domain", 0, 274, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("The Great Gatsby", "F. Scott Fitzgerald", "Public Domain", 0, 411, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("The Picture of Dorian Gray", "Oscar Wilde", "Public Domain", 0, 189, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("Alice's Adventures in Wonderland", "Lewis Carroll", "Public Domain", 0, 899, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("Dracula", "Bram Stoker", "Public Domain", 0, 651, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("The Strange Case of Dr.Jekyll and Mr.Hyde", "Robert Louis Stevenson", "Public Domain", 0, 211, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("Don Quixote", "Miguel de Cervantes Saavedra", "Public Domain", 0, 999, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("The Tempest", "William Shakespeare", "Public Domain", 0, 415, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("The Count of Monte Cristo", "Alexandre Dumas", "Public Domain", 0, 415, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");
INSERT INTO book (name, writer, publisher, price, pages, cid, lid, bookUrl, bookImage) values ("The Scarlet Letter", "Nathaniel Hawthorne", "Public Domain", 0, 415, 100, 201, "https://storage.googleapis.com/ebook_sample/moby_dick_short.txt", "https://storage.googleapis.com/ebook_sample/thegreatgatsby.jpg");